### ISSUE TITLE
Hello, this is the only place I could find to leave a comment.  Sorry if it's in the wrong place.

### ISSUE THREAD

**Issue by whitebalanceinc** [cyraxx/xkeys-atem-remote#2]
Hello,

Are there any bits of code in this that could get the xKey 124 T-bar to automate this in DaVinci Resolve application:

https://drive.google.com/file/d/1W7xLKw4FsEekt6M_v2bCRBTV4Pu5a21Z/view?usp=sharing

Resolve's wipe function places two images over each other in the exact same spot in the GUI.  You can then “switch” between the two images just like you would “switch” between two live video feeds in a control room.  Just inside the app.  This is also output through video hardware to your broadcast monitor.

When you initiate the wipe function, a visible line appears, splitting the two images in half.  You can then click, hold, and drag a mouse or pen tablet, and drag either way to reveal more or less of each image.  Effectively cropping the image your are dragging over and revealing more of the image you are dragging from.

If you have BM's $30k Black Magic Advanced panel T-bar, you can use it's T-bar to wipe between the images.  I'm assuming BM's DaVinci Resolve uses the same code for their Advanced Panel T-bar, as BM's ATEM uses for the a T-bar on an external controller.  So technically Resolve should be "listening" for a T-bar

The physical wiping of the line itself could be a "left mouse button down and hold" but assigned to the T-bar instead of the mouse.

I see the code above. It seems like it will tell a listening app or device that the T-bar has moved, and the position it's in. But is there anything that will then connect it to an action like the wipe in the video above?

Is it somewhere in here:

XKE124TBAR: {
identifier: 'XKE-124 T-bar',
productId: [1275,1276,1277,1278],
columns: 16,
rows: 8,
hasPS: false,
hasTbar: true,
tbarByte: 30,
tbarByteRaw: 31,
banks: 2,
bankSize: 128,
disableKeys: [108,109,110,111]

Do I have to assign something from the PI engineering doc to the "tbarByte" or another line?:

file:///Users/ernestsavage/Downloads/non-PC/xke124Tbarreport.htm

Thanks. Sorry I'm such a noob, I just need this one command that I thought I could just copy and paste code for.

**Comment by cyraxx** [comment]
Hi!

Funny coincidence that you're asking about the T-bar right now, as I'm about to add support for it to this project so the XKE-124 can be used to control ATEM switchers.

Doing something similar for DaVinci Resolve should certainly be possible - however, it would be an entirely different project that would need to be more or less written from scratch specifically to control Resolve instead of ATEM.

As I don't use Resolve myself and don't currently have any plans to write a remote control app for it I'm afraid there's nothing I can do for you here.

**Comment by whitebalanceinc** [comment]
Is there any way to ask if the code is similar for the AETM as Resolve for T-bar control, and to share whatever you get?

Thanks!

whitebalanceinc@gmail.com
323-497-4963

**Comment by whitebalanceinc** [comment]
Since I’m watching this thread, I should get notified when you add code to control switching on the AETM?

Thanks!!!

whitebalanceinc@gmail.com
323-497-4963

**Comment by cyraxx** [comment]
I just added T-bar support. The relevant code is here: https://github.com/cyraxx/xkeys-atem-remote/commit/9dc0923b151b0c01de03de8ff6a352d52ac58a9b#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346

But honestly I doubt it'll be of much use to you. Interfacing with the T-bar itself is pretty trivial, it's talking to the device you're controlling that will be most of the effort - and that's where ATEM and Resolve have completely separate APIs.

**Comment by whitebalanceinc** [comment]
Thanks so much.  As someone just starting out, this is very helpful.  I’m
going to look up the definitions of each line.  Slowly start to engineer
what I want.

Is this

Yes Resolve’s API is very tight, as BM is trying to sell hardware.  I
totally understand.  To be honest I don’t know how the can pull of the
feats they have been in recent years.  Must be a serious drain on profits.

Thanks!

whitebalanceinc@gmail.com
323-497-4963

On Jan 17, 2021, at 9:07 AM, Andreas Reich <notifications@github.com> wrote:

﻿

I just added T-bar support. The relevant code is here: 9dc0923
#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346
<https://github.com/cyraxx/xkeys-atem-remote/commit/9dc0923b151b0c01de03de8ff6a352d52ac58a9b#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346>

But honestly I doubt it'll be of much use to you. Interfacing with the
T-bar itself is pretty trivial, it's talking to the device you're
controlling that will be most of the effort - and that's where ATEM and
Resolve have completely separate APIs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cyraxx/xkeys-atem-remote/issues/2#issuecomment-761845023>,
or unsubscribe
